# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    cpus_per_task: 4
    nodes: 1
    mem_gb: 128
    additional_parameters:
    timeout_min: 10 
    gres: gpu:1
    tasks_per_node: 1
