# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    cpus_per_task: 2
    gpus_per_task: 1
    tasks_per_node: 1
    nodes: 1
    mem_gb: 8
    additional_parameters:
    timeout_min: 60 # 24 hours by default